duraark-pointcloud-viewer:
  build: .
  command: nodemon -w /code app/index.js
  ports:
    - "5016:5016"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - .:/opt/duraark-pointcloud-viewer
